### ISSUE TITLE
[Feature Request] Add support for disabling signature validation

### ISSUE THREAD

**Issue by tp-woven** [cduvray/jwt-authorizer#1]
`jsonwebtoken` exposes the [`insecure_disable_signature_validation`](https://docs.rs/jsonwebtoken/latest/jsonwebtoken/struct.Validation.html#method.insecure_disable_signature_validation) method, that allows for decoding JWTs without validating their signature. This is useful is some use-cases where the service can assume that the token was already validated (in our case, it is done by the service mesh) and only needs to access the encoded claims.

However, from what I can tell from the code [here](https://github.com/cduvray/jwt-authorizer/blob/main/jwt-authorizer/src/authorizer.rs#L130), the `Validation` is never exposed outside the layer and there is no way to configure it.

**Comment by cduvray** [comment]
yes, I'd like to expose some validation configuration, I hope I will be able to make a pull request in a few days or so.

**Comment by tp-woven** [comment]
This is great, thank you @cduvray!
