### ISSUE TITLE
Allow optional claims

### ISSUE THREAD

**Issue by arlyon** [cduvray/jwt-authorizer#12]
It would be nice to, rather than outright rejecting missing claims, to only require claims for those handlers that have an extractor for it. Similarly, `Option<Claim>` should go through as long as there is:

- a) a valid Claim
- b) no token provided at all

With a little tweaking (namely removing the 'missing' error variant) we can get part-way there, but because we simply return a 500 error when we can't get the token, it fails. I think the solution is to keep the missing variant, and have AuthError be the rejection type for the extractor as well, rather than just the middleware.

**Comment by cduvray** [comment]
Hi, I've tried to adapt the extractor, so that it could deal with Option (optional extraction) more "nicely". (PR #31)
