### ISSUE TITLE
Allow usage of variables within `check` (closures can only be coerced to `fn` types if they do not capture any variables)

### ISSUE THREAD

**Issue by lcmgh** [cduvray/jwt-authorizer#32]
Hi!

I want to check my custom claim against a predefined config. Therefore I have to move a variable into the closure of `fn check.

https://docs.rs/jwt-authorizer/latest/jwt_authorizer/layer/struct.JwtAuthorizer.html#method.check

But when trying to use a variable within the check callback I am facing `closures can only be coerced to `fn` types if they do not capture any variables`

**Comment by cduvray** [comment]
Hi, the PR #36, replacing a function pointer by a Fn() trait should fix you problem,  

https://github.com/cduvray/jwt-authorizer/blob/20b604e2c8d7a6ac9c210dcb075a6bb89b3f3dc6/jwt-authorizer/src/builder.rs#L157-L159

**Comment by lcmgh** [comment]
Hi! Thanks for the PR.

It actually does not allow to move a custom variable into the closure.

```rust
 let c_clone = c.clone(); // some clonable config struct
 let auth: Authorizer = JwtAuthorizer::from_oidc(&c.provider_url)
      .check(|claims| {
          let a = c_clone; // for checking claims against my config
          true
      })
      .build()
      .await
      .unwrap();
```

fails to compile with

`note: closures can only be coerced to `fn` types if they do not capture any variables`
