### ISSUE TITLE
When using discovery url and a self signed certificate for the provider a connection cannot be established

### ISSUE THREAD

**Issue by NotNorom** [cduvray/jwt-authorizer#41]
Hi!

I've ran into a scenario where a keycloak instance is running behind a self signed ssl certificate. I am unable to change that fact as it's company policy. They're doing custom CA stuff, blah blah.

So right now I am looking for a way to either configure the `reqwest::Client` inside the `pub async fn discover_jwks(issuer: &str) -> Result<String, InitError>` function or pass my own client.

I'd prefer passing one, as I am already creating one for use in other parts of my program.

What do you think?
I'm also more than down to create a pull request to help with this :)

**Comment by cduvray** [comment]
closing this, #42 merged.
