### ISSUE TITLE
Support extracting claims from a cookie

### ISSUE THREAD

**Issue by arlyon** [cduvray/jwt-authorizer#9]
Hi! Nice library. I was trying to use this to write my own extractor for jwt claims from a cookie (with `SameSite=Strict`) but I noticed that there is no way to get a raw Authorizer. I plan on contributing this, I just wanted to open the issue first.

**Comment by arlyon** [comment]
It would! Thanks for doing that!

**Comment by arlyon** [comment]
By the way, Hanko looks obscenely cool. 🔥

**Comment by like-a-bause** [comment]
Thanks. Be sure to tell your friends and family! 😉

**Comment by like-a-bause** [comment]
#10 is merged.

**Comment by arlyon** [comment]
Nice!

**Comment by cduvray** [comment]
Hi, 

I think there's a mistake. I've tested this and it does not work. 
The code:  `request.extensions().get::<Cookies>()` retrieves the cookie from a jar (tower middleware) not from the request. 
Whereas the token should be in the request (header Cookie), am I right?
To retrieve the cookie this should be :
`headers.typed_get::<headers::Cookie>()`.

I can fix this but just I want to be sure that I'm not mistaken.

**Comment by like-a-bause** [comment]
Hey. This is why I labeled the PR as "naive". 
I thought it would be a good Idea to re-use a tower layer instead of parsing the cookie in this layer.
I think it depends on the use-case which method is better. If the application is interested in more than a jwt cookie it would be better to use the tower-cookie middleware. Otherwise your approach seems more straight forward.

Maybe this could be switched via a feature-flag?

**Comment by cduvray** [comment]
In fact, I added an integration test that does not pass with the tower-cookies implementation,
I presume that a tower-cookie layer (CookieManagerLayer) should be added the request processing but this seems too complicated.

If the need is just to get the token that is in a cookie sent by the client I'd prefer keeping this simple.

**Comment by arlyon** [comment]
I have no opinion on layer vs not, however I will add that my PR _also_ adds a test for the cookie layer which does work

https://github.com/cduvray/jwt-authorizer/pull/16/files#diff-f48820951f7fed056703063079986fa8650146a97c22ef3120ad0baf73e7c548R306-R334
